[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.websocket"

[deploy]
startCommand = "node dist/src/server/websocket-server.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
